spring:
  application:
    name: Lizyea

  datasource:
    url: jdbc:mysql://localhost:3306/myapp
    username: root
    password: qwetarget1

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672